export const CACHE_KEYS = {
  API_TOKEN_KEY: "API_TOKEN",
  ROLE_KEY: "ROLE",
  AUID_KEY: "AUID",
  USERNAME_KEY: "USERNAME",
  HEAD_PIC_KEY: "HEAD_PIC",
  ACTIVE_TAB_KEY: "ACTIVE_TAB",
  HISTORY_PATH_KEY: "HISTORY_PATH"
}